import { spawn, spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { performance } from "node:perf_hooks";
import { resolve } from "node:path";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { AUTOMOTIVE_CLASSIFICATION_VERSION, classifyAutomotiveCategory } from "../src/commerce/classification/automotive/index.js";
import { buildAtomicRegistryApplyPayload, measureAtomicRegistryApplyPayload, validateAtomicRegistryApplyPayload, type AtomicRegistryApplyPayload } from "../src/commerce/registry/apply-payload.js";
import { diffCommerceRegistryState } from "../src/commerce/registry/diff.js";
import { RegistrySyncError } from "../src/commerce/registry/errors.js";
import { buildCommerceRegistrySyncPlan } from "../src/commerce/registry/planner.js";
import { COMMERCE_REGISTRY_SYNC_CONFIG_VERSION, type CommerceRegistrySyncPlan } from "../src/commerce/registry/types.js";
import { applyCommerceRegistrySync, callAtomicRegistryApplyRpc, registryApplyClientFromSupabase } from "../src/server/registry/executor.js";
import { loadCurrentCommerceRegistryState, registryReadClientFromSupabase, type RegistryReadClient, type RegistryReadQuery } from "../src/server/registry/current-state.js";
import { TaxonomyTree } from "../src/taxonomy/tree.js";
import { snapshotToTaxonomyTree, validateAutomotiveTaxonomySnapshot } from "../src/taxonomy/automotive-snapshot.js";

const EXPECTED_CHECKSUM="c9e15babf11f24faa009641f174810eabb1459a705d74b8d4d0c3a6c1e77ded2";
const root=resolve(import.meta.dirname,"..");
const fixture=resolve(root,"tests/fixtures/meli-automotive-taxonomy.snapshot.json");
const checked="2026-08-24T12:00:00.000Z";
const metrics:Record<string,unknown>={};
const ensure: (ok: unknown, code: string) => asserts ok = (ok,code) => {if(!ok)throw new Error(code);};
const delay=(ms:number)=>new Promise(r=>setTimeout(r,ms));

function localEnv(){
 const cli=resolve(root,"node_modules/.bin/supabase.CMD");
 const p=spawnSync(cli,["status","-o","env"],{cwd:root,encoding:"utf8",windowsHide:true,shell:process.platform==="win32"});
 ensure(p.status===0,"LOCAL_SUPABASE_STATUS_FAILED"); const out:Record<string,string>={};
 for(const line of p.stdout.split(/\r?\n/)){const m=/^([A-Z0-9_]+)=(.*)$/.exec(line);if(m)out[m[1]!]=m[2]!.replace(/^"|"$/g,"");}
 const url=new URL(out.API_URL??""); ensure(["127.0.0.1","localhost"].includes(url.hostname),"LOCAL_ONLY_GUARD_FAILED");
 ensure(url.protocol==="http:","LOCAL_ONLY_GUARD_FAILED");
 const secret=out.SECRET_KEY??out.SERVICE_ROLE_KEY; ensure(secret&&out.ANON_KEY,"LOCAL_CREDENTIALS_MISSING");
 return {url:url.toString().replace(/\/$/,""),secret,anon:out.ANON_KEY!};
}
function client(url:string,key:string){return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});}
function runPsql(sql:string){return new Promise<string>((res,rej)=>{const c=spawn("docker",["exec","supabase_db_AutoAchado.AI","psql","-U","postgres","-d","postgres","-AtX","-v","ON_ERROR_STOP=1","-c",sql],{windowsHide:true});let o="";c.stdout.on("data",x=>o+=String(x));c.stderr.on("data",()=>{});c.on("error",()=>rej(new Error("LOCAL_PSQL_FAILED")));c.on("close",n=>n===0?res(o.trim()):rej(new Error("LOCAL_PSQL_FAILED")));});}
const q=(v:string)=>`'${v.replaceAll("'","''")}'`;
function buildPlan(tree:TaxonomyTree,sourceVersion:string,checkedAt:string):CommerceRegistrySyncPlan{return buildCommerceRegistrySyncPlan({context:{marketplaceKey:"MERCADO_LIVRE",siteId:"MLB",verticalKey:"AUTOMOTIVE",rootExternalCategoryId:"MLB5672",sourceVersion,expectedClassificationVersion:AUTOMOTIVE_CLASSIFICATION_VERSION,configVersion:COMMERCE_REGISTRY_SYNC_CONFIG_VERSION,checkedAt},taxonomyTree:tree,classifyCategory:(id,t)=>{const x=classifyAutomotiveCategory(id,t);return{externalCategoryId:x.categoryId,scopeStatus:x.scopeStatus,priorityTier:x.priorityTier,familyKey:x.familyKey,commercialFamilyKeyDefault:x.commercialFamilyKeyDefault,ruleId:x.ruleId,classificationVersion:x.classificationVersion,reason:x.reason};}});}
function trackingRead(c:SupabaseClient,stats:{categories:number;mappings:number}):RegistryReadClient{const base=registryReadClientFromSupabase(c);return{from(table){const wrap=(query:RegistryReadQuery):RegistryReadQuery=>({select(cols){return wrap(query.select(cols));},eq(col,val){return wrap(query.eq(col,val));},order(col,opt){return wrap(query.order(col,opt));},range(from,to){if(table==="marketplace_categories")stats.categories++;else stats.mappings++;return query.range(from,to);}});return wrap(base.from(table));}};}
async function counts(c:SupabaseClient){const one=async(t:string)=>{const r=await c.from(t).select("*",{count:"exact",head:true});ensure(!r.error,"DATA_API_COUNT_FAILED");return r.count??-1;};return{categories:await one("marketplace_categories"),mappings:await one("vertical_category_mappings")};}
async function state(c:SupabaseClient,plan:CommerceRegistrySyncPlan,stats:{categories:number;mappings:number}){return loadCurrentCommerceRegistryState({client:trackingRead(c,stats),marketplaceKey:"MERCADO_LIVRE",siteId:"MLB",verticalKey:"AUTOMOTIVE",rootExternalCategoryId:"MLB5672",desiredExternalCategoryIds:plan.categories.map(x=>x.externalCategoryId)});}
async function hash(kind:"uuid"|"timestamps"){return runPsql(kind==="uuid"?"select md5(string_agg(external_category_id||marketplace_category_id::text,'' order by external_category_id)) from public.marketplace_categories where marketplace_key='MERCADO_LIVRE' and site_id='MLB'":"select md5(coalesce((select string_agg(external_category_id||first_seen_at::text||last_seen_at::text||source_checked_at::text||updated_at::text,'' order by external_category_id) from public.marketplace_categories where marketplace_key='MERCADO_LIVRE' and site_id='MLB'),'')||coalesce((select string_agg(c.external_category_id||m.decided_at::text||m.updated_at::text,'' order by c.external_category_id) from public.vertical_category_mappings m join public.marketplace_categories c using(marketplace_category_id) where c.marketplace_key='MERCADO_LIVRE' and c.site_id='MLB'),''))");}
function clonePayload(p:AtomicRegistryApplyPayload){return structuredClone(p) as any;}

const raw=await readFile(fixture); const checksum=createHash("sha256").update(raw).digest("hex");ensure(checksum===EXPECTED_CHECKSUM,"SNAPSHOT_CHECKSUM_MISMATCH");
const parsed=validateAutomotiveTaxonomySnapshot(JSON.parse(raw.toString("utf8"))).snapshot;const tree=snapshotToTaxonomyTree(parsed);
let t=performance.now();const plan=buildPlan(tree,parsed.sourceVersion,checked);metrics.plannerMs=performance.now()-t;
t=performance.now();const payload=buildAtomicRegistryApplyPayload(plan);metrics.payloadBuildMs=performance.now()-t;
t=performance.now();const serializedPayload=JSON.stringify(payload);metrics.payloadSerializationMs=performance.now()-t;const measure=measureAtomicRegistryApplyPayload(payload);metrics.payloadBytes=measure.bytes;metrics.payloadKiB=measure.kibibytes;metrics.payloadMiB=measure.mebibytes;metrics.requestBytes=Buffer.byteLength(JSON.stringify({p_payload:payload}));ensure(Buffer.byteLength(serializedPayload)===measure.bytes,"PAYLOAD_SERIALIZATION_MISMATCH");
ensure(payload.rows.length===3269&&measure.bytes===1603538,"FULL_PAYLOAD_BASELINE_FAILED");
const env=localEnv();const service=client(env.url,env.secret);const anon=client(env.url,env.anon);const rawApplyClient=registryApplyClientFromSupabase(service);let rpcCalls=0;const applyClient={rpc(...args:Parameters<typeof rawApplyClient.rpc>){rpcCalls++;return rawApplyClient.rpc(...args);}};
ensure((await counts(service)).categories===0,"LOCAL_DB_NOT_FRESH");
t=performance.now();const first=await applyCommerceRegistrySync({client:applyClient,plan});metrics.firstApplyMs=performance.now()-t;metrics.responseBytes=Buffer.byteLength(JSON.stringify(first));
ensure(first.categories.inserted===3269&&first.mappings.inserted===3269&&first.effective.activeMappings===3269,"FIRST_APPLY_FAILED");
ensure(first.effective.allowed===470&&first.effective.review===1950&&first.effective.excluded===849&&first.effective.unknown===0&&first.effective.tierA===28&&first.effective.tierB===116&&first.effective.tierC===326&&first.effective.automaticEligible===144,"EFFECTIVE_COUNTS_FAILED");
ensure(JSON.stringify(await counts(service))===JSON.stringify({categories:3269,mappings:3269}),"DB_COUNTS_FAILED");
const integrity=await runPsql("select (select count(*) from public.marketplace_categories c where c.site_id='MLB' and c.external_category_id<>'MLB5672' and c.parent_marketplace_category_id is null)||'|'||(select count(*) from public.marketplace_categories c left join public.marketplace_categories p on p.marketplace_category_id=c.parent_marketplace_category_id where c.site_id='MLB' and c.parent_marketplace_category_id is not null and p.marketplace_category_id is null)||'|'||(select count(*)-count(distinct marketplace_category_id) from public.marketplace_categories where site_id='MLB')");ensure(integrity==="0|0|0","PARENT_UUID_INTEGRITY_FAILED");
const pages={categories:0,mappings:0};t=performance.now();const current=await state(service,plan,pages);metrics.currentStateReadMs=performance.now()-t;ensure(current.categories.length===3269&&current.mappings.length===3269&&current.controlledMappingExternalCategoryIds.length===3269,"CURRENT_STATE_TRUNCATED");ensure(pages.categories>=4&&pages.mappings>=4,"REAL_PAGINATION_FAILED");
t=performance.now();const firstDiff=diffCommerceRegistryState(plan,current);metrics.diffMs=performance.now()-t;ensure(firstDiff.summary.categories.unchanged===3269&&firstDiff.summary.mappings.unchanged===3269,"FIRST_DIFF_FAILED");
const ts0=await hash("timestamps");const uuid0=await hash("uuid");t=performance.now();const replay=await applyCommerceRegistrySync({client:applyClient,plan});metrics.replayMs=performance.now()-t;ensure(replay.categories.unchanged===3269&&replay.mappings.unchanged===3269&&await hash("timestamps")===ts0,"REPLAY_CHURN");
const checkedPlan=buildPlan(tree,parsed.sourceVersion,"2026-08-25T12:00:00.000Z");t=performance.now();const checkedResult=await applyCommerceRegistrySync({client:applyClient,plan:checkedPlan});metrics.checkedAtReplayMs=performance.now()-t;ensure(checkedResult.categories.unchanged===3269&&checkedResult.mappings.unchanged===3269&&await hash("timestamps")===ts0,"CHECKEDAT_CHURN");
const sourcePlan=buildPlan(tree,"test-source-drift/v2","2026-08-26T12:00:00.000Z");t=performance.now();const sourceResult=await applyCommerceRegistrySync({client:applyClient,plan:sourcePlan});metrics.sourceDriftMs=performance.now()-t;ensure(sourceResult.categories.updated===3269&&sourceResult.mappings.unchanged===3269&&await hash("uuid")===uuid0,"SOURCE_DRIFT_FAILED");
let latest=buildAtomicRegistryApplyPayload(sourcePlan);const classifier=clonePayload(latest);classifier.context.classificationVersion="automotive-classifier/mlb/test-v2";validateAtomicRegistryApplyPayload(classifier);t=performance.now();const classResult=await callAtomicRegistryApplyRpc(applyClient,classifier);metrics.classifierDriftMs=performance.now()-t;ensure(classResult.categories.unchanged===3269&&classResult.mappings.updated===3269,"CLASSIFIER_DRIFT_FAILED");latest=classifier;
const childCounts=new Map<string,number>();for(const x of plan.categories)if(x.parentExternalCategoryId)childCounts.set(x.parentExternalCategoryId,(childCounts.get(x.parentExternalCategoryId)??0)+1);const candidate=plan.categories.find(x=>x.isLeaf&&x.parentExternalCategoryId&&(childCounts.get(x.parentExternalCategoryId)??0)>1&&plan.mappings.find(m=>m.externalCategoryId===x.externalCategoryId)?.priorityTier==="A");ensure(candidate,"MANUAL_CANDIDATE_MISSING");const id=candidate.externalCategoryId;
await runPsql(`update public.vertical_category_mappings vm set scope_status='REVIEW',priority_tier=null,manual_override=true,decision_source='MANUAL',decision_reason='local-e2e',decided_at='2026-08-27T12:00:00Z' from public.marketplace_categories c where c.marketplace_category_id=vm.marketplace_category_id and c.external_category_id=${q(id)} and c.site_id='MLB'`);const manualUpdated=await runPsql(`select vm.updated_at::text from public.vertical_category_mappings vm join public.marketplace_categories c using(marketplace_category_id) where c.external_category_id=${q(id)} and c.site_id='MLB'`);t=performance.now();const manualResult=await callAtomicRegistryApplyRpc(applyClient,latest);metrics.manualApplyMs=performance.now()-t;ensure(manualResult.mappings.manualOverrideSkipped===1,"MANUAL_SKIP_FAILED");ensure(await runPsql(`select (vm.manual_override and vm.scope_status='REVIEW' and vm.priority_tier is null and vm.updated_at::text=${q(manualUpdated)})::text from public.vertical_category_mappings vm join public.marketplace_categories c using(marketplace_category_id) where c.external_category_id=${q(id)} and c.site_id='MLB'`)==="true","MANUAL_PRESERVATION_FAILED");
const reduced=clonePayload(latest);reduced.rows=reduced.rows.filter((x:any)=>x.externalCategoryId!==id);reduced.context.expectedCategoryCount--;reduced.context.expectedMappingCount--;reduced.context.expectedAutomaticEligibleCount--;validateAtomicRegistryApplyPayload(reduced);t=performance.now();const inactive=await callAtomicRegistryApplyRpc(applyClient,reduced);metrics.inactivationMs=performance.now()-t;ensure(inactive.mappings.inactivated===1,"INACTIVATION_FAILED");ensure(await runPsql(`select (c.active and not vm.active and vm.manual_override)::text from public.marketplace_categories c join public.vertical_category_mappings vm using(marketplace_category_id) where c.external_category_id=${q(id)} and c.site_id='MLB'`)==="true","CATEGORY_ABSENCE_SAFETY_FAILED");t=performance.now();const returned=await callAtomicRegistryApplyRpc(applyClient,latest);metrics.reactivationMs=performance.now()-t;ensure(returned.mappings.reactivated===1,"REACTIVATION_FAILED");
const candidateUuid=await runPsql(`select marketplace_category_id from public.marketplace_categories where external_category_id=${q(id)} and site_id='MLB'`);await runPsql(`update public.marketplace_categories set active=false where external_category_id=${q(id)} and site_id='MLB'`);t=performance.now();const factual=await callAtomicRegistryApplyRpc(applyClient,latest);metrics.categoryReactivationMs=performance.now()-t;ensure(factual.categories.reactivated===1&&await runPsql(`select marketplace_category_id from public.marketplace_categories where external_category_id=${q(id)} and site_id='MLB'`)===candidateUuid,"CATEGORY_REACTIVATION_FAILED");
const small:any={context:{contractVersion:"commerce-registry-apply/v1",marketplaceKey:"MERCADO_LIVRE",siteId:"LOCAL_PARENT",verticalKey:"AUTOMOTIVE",rootExternalCategoryId:"R",sourceVersion:"s",classificationVersion:"c",configVersion:"v",checkedAt:checked,expectedCategoryCount:3,expectedMappingCount:3,expectedAutomaticEligibleCount:0},rows:[{externalCategoryId:"R",parentExternalCategoryId:null,name:"Root",pathExternalIds:["R"],pathNames:["Root"],isLeaf:false,scopeStatus:"REVIEW",priorityTier:null,familyKey:null,commercialFamilyKeyDefault:null,classificationRule:"r",decisionReason:null},{externalCategoryId:"A",parentExternalCategoryId:"R",name:"A",pathExternalIds:["R","A"],pathNames:["Root","A"],isLeaf:false,scopeStatus:"REVIEW",priorityTier:null,familyKey:null,commercialFamilyKeyDefault:null,classificationRule:"a",decisionReason:null},{externalCategoryId:"C",parentExternalCategoryId:"A",name:"C",pathExternalIds:["R","A","C"],pathNames:["Root","A","C"],isLeaf:true,scopeStatus:"REVIEW",priorityTier:null,familyKey:null,commercialFamilyKeyDefault:null,classificationRule:"c",decisionReason:null}]};validateAtomicRegistryApplyPayload(small);await callAtomicRegistryApplyRpc(applyClient,small);const smallUuid=await runPsql("select marketplace_category_id from public.marketplace_categories where site_id='LOCAL_PARENT' and external_category_id='C'");const moved=clonePayload(small);moved.context.checkedAt="2026-08-28T12:00:00Z";moved.rows[1].isLeaf=true;moved.rows[2].parentExternalCategoryId="R";moved.rows[2].pathExternalIds=["R","C"];moved.rows[2].pathNames=["Root","C"];validateAtomicRegistryApplyPayload(moved);t=performance.now();const movedResult=await callAtomicRegistryApplyRpc(applyClient,moved);metrics.parentChangeMs=performance.now()-t;ensure(movedResult.categories.updated===2&&await runPsql("select marketplace_category_id from public.marketplace_categories where site_id='LOCAL_PARENT' and external_category_id='C'")===smallUuid,"PARENT_CHANGE_FAILED");
const hold=runPsql("begin;select pg_advisory_xact_lock(hashtextextended('autoachado:commerce-registry:MERCADO_LIVRE:MLB',0));select pg_sleep(3);rollback");await delay(500);let locked=false;try{await applyCommerceRegistrySync({client:applyClient,plan});}catch(e){locked=e instanceof RegistrySyncError&&e.code==="REGISTRY_SYNC_LOCKED";}ensure(locked,"LOCK_ERROR_MAPPING_FAILED");await hold;t=performance.now();await callAtomicRegistryApplyRpc(applyClient,latest);metrics.lockReleaseApplyMs=performance.now()-t;
const deniedId="LOCAL_DENIED";const ins=await service.from("marketplace_categories").insert({marketplace_key:"MERCADO_LIVRE",site_id:"MLB",external_category_id:deniedId,name:"Denied",config_version:"v"});ensure(ins.error,"DIRECT_INSERT_NOT_DENIED");const upd=await service.from("marketplace_categories").update({name:"Denied"}).eq("site_id","MLB").eq("external_category_id",id);ensure(upd.error,"DIRECT_UPDATE_NOT_DENIED");const anonResult=await anon.rpc("apply_commerce_registry_sync",{p_payload:small});ensure(anonResult.error,"ANON_RPC_NOT_DENIED");
const audit=await runPsql("select (select count(*) from public.marketplace_categories c where c.parent_marketplace_category_id is not null and not exists(select 1 from public.marketplace_categories p where p.marketplace_category_id=c.parent_marketplace_category_id))||'|'||(select count(*) from public.vertical_category_mappings m where not exists(select 1 from public.marketplace_categories c where c.marketplace_category_id=m.marketplace_category_id))||'|'||(select count(*) from (select marketplace_key,site_id,external_category_id,count(*) from public.marketplace_categories group by 1,2,3 having count(*)>1)x)||'|'||(select count(*) from (select vertical_key,marketplace_category_id,count(*) from public.vertical_category_mappings group by 1,2 having count(*)>1)x)||'|'||(select count(*) from public.vertical_category_mappings where not ((scope_status='ALLOWED' and priority_tier in('A','B','C')) or (scope_status in('REVIEW','EXCLUDED','UNKNOWN') and priority_tier is null)))||'|'||(select count(*) from public.vertical_category_mappings where manual_override<>(decision_source='MANUAL'))");ensure(audit==="0|0|0|0|0|0","DB_INTEGRITY_FAILED");
Object.assign(metrics,{snapshotChecksum:checksum,rows:3269,categoryPages:pages.categories,mappingPages:pages.mappings,networkCalls:{rpc:rpcCalls,readerRanges:pages.categories+pages.mappings},first,sourceResult,classResult,manualResult,inactive,returned,factual,movedResult,integrity:audit,localOnly:true});process.stdout.write(JSON.stringify(metrics)+"\n");
