import type {
  AutomotiveCategoryRule,
  AutomotiveClassifierRules,
  AutomotivePriorityTier,
} from "./types.js";
import {
  AUTOMOTIVE_CLASSIFICATION_VERSION,
  AUTOMOTIVE_ROOT_CATEGORY_ID,
} from "./types.js";

const allowed = (
  categoryId: string,
  ruleId: string,
  priorityTier: AutomotivePriorityTier,
  familyKey: string,
): AutomotiveCategoryRule => ({
  categoryId, ruleId, scopeStatus: "ALLOWED", priorityTier, familyKey,
  commercialFamilyKeyDefault: null, reason: "EXACT_OVERRIDE",
});

const review = (
  categoryId: string,
  ruleId: string,
  reason: AutomotiveCategoryRule["reason"] = "RESIDUAL_REVIEW",
): AutomotiveCategoryRule => ({
  categoryId, ruleId, scopeStatus: "REVIEW", priorityTier: null, familyKey: null,
  commercialFamilyKeyDefault: null, reason,
});

const excluded = (
  categoryId: string,
  ruleId: string,
  reason: AutomotiveCategoryRule["reason"] = "MVP_VEHICLE_SCOPE_EXCLUSION",
): AutomotiveCategoryRule => ({
  categoryId, ruleId, scopeStatus: "EXCLUDED", priorityTier: null, familyKey: null,
  commercialFamilyKeyDefault: null, reason,
});

const allowedAncestor = (
  categoryId: string,
  ruleId: string,
  priorityTier: AutomotivePriorityTier,
  familyKey: string,
): AutomotiveCategoryRule => ({
  ...allowed(categoryId, ruleId, priorityTier, familyKey), reason: "ALLOWED_ANCESTOR",
});
const reviewAncestor = (categoryId: string, ruleId: string): AutomotiveCategoryRule => ({
  ...review(categoryId, ruleId, "REVIEW_ANCESTOR"),
});
const excludedAncestor = (
  categoryId: string,
  ruleId: string,
  reason: AutomotiveCategoryRule["reason"] = "EXCLUDED_ANCESTOR",
): AutomotiveCategoryRule => ({ ...excluded(categoryId, ruleId, reason) });

const exactRules: AutomotiveCategoryRule[] = [
  review(AUTOMOTIVE_ROOT_CATEGORY_ID, "root.mixed-review", "MIXED_BRANCH_REVIEW"),
  excluded("MLB377674", "services.self", "SERVICE_CATEGORY"),
  excluded("MLB457400", "tire-installation.service", "SERVICE_CATEGORY"),
  excluded("MLB458209", "complete-motorcycles.self", "COMPLETE_VEHICLE_CATEGORY"),
  excluded("MLB419936", "heavy-parts.self"),
  excluded("MLB438364", "heavy-accessories.self"),
  excluded("MLB6005", "marine-accessories.self"),
  excluded("MLB456046", "marine-parts.self"),
  excluded("MLB45468", "gnv.self"),

  review("MLB2238", "tires.root-review", "MIXED_BRANCH_REVIEW"),
  allowed("MLB2233", "tires.car-pickup", "A", "tires"),
  allowed("MLB3933", "tires.motorcycle", "A", "tires"),
  review("MLB22223", "tires.other-review"),
  review("MLB271606", "tires.tubes-review"),
  review("MLB456076", "tires.sealants-review"),
  excluded("MLB420223", "tires.quadricycle"),
  excluded("MLB429043", "tires.industrial"),
  excluded("MLB433027", "tires.truck"),
  excluded("MLB433028", "tires.agricultural"),
  excluded("MLB438193", "tires.aircraft"),
  excluded("MLB438194", "tires.bicycle"),
  excluded("MLB439738", "tires.scooter"),
  excluded("MLB457401", "tires.cart"),

  review("MLB255788", "wheels.root-review", "MIXED_BRANCH_REVIEW"),
  allowed("MLB4860", "wheels.car-pickup", "B", "wheels"),
  allowed("MLB22727", "wheels.motorcycle", "B", "wheels"),
  excluded("MLB432914", "wheels.quadricycle"),
  excluded("MLB438045", "wheels.truck"),
  review("MLB255789", "wheels.other-review"),
  review("MLB455309", "wheels.patch-stickers-review", "LOW_BREADTH_MVP"),

  review("MLB456111", "lubricants.root-review", "MIXED_BRANCH_REVIEW"),
  allowed("MLB194025", "lubricants.car-pickup.self", "A", "lubricants_fluids"),
  allowed("MLB439944", "lubricants.motorcycle.self", "A", "lubricants_fluids"),
  allowed("MLB437274", "lubricants.greases", "B", "lubricants_fluids"),
  allowed("MLB439463", "lubricants.fluids.self", "B", "lubricants_fluids"),
  review("MLB456112", "lubricants.other-review"),
  excluded("MLB456115", "lubricants.heavy.self"),
  excluded("MLB456116", "lubricants.marine.self"),
  excluded("MLB456130", "lubricants.agro-industrial.self"),

  review("MLB22693", "car-parts.root-review", "MIXED_BRANCH_REVIEW"),
  allowed("MLB191834", "car-parts.filters.self", "A", "filters"),
  allowed("MLB6789", "car-parts.brakes.self", "B", "brakes"),
  allowed("MLB47097", "car-parts.brakes.pads", "B", "brakes"),
  allowed("MLB47098", "car-parts.brakes.discs", "B", "brakes"),
  allowed("MLB47099", "car-parts.brakes.calipers", "B", "brakes"),
  allowed("MLB47100", "car-parts.brakes.kits", "B", "brakes"),
  allowed("MLB63581", "car-parts.brakes.drums", "B", "brakes"),
  allowed("MLB458330", "car-parts.brakes.pad-kits", "B", "brakes"),
  allowed("MLB191708", "car-parts.brakes.shoes", "B", "brakes"),
  allowed("MLB458334", "car-parts.brakes.shoe-kits", "B", "brakes"),
  allowed("MLB458335", "car-parts.brakes.shoe-sets", "B", "brakes"),
  review("MLB47094", "car-parts.brakes.other-review"),
  allowed("MLB22648", "car-parts.suspension.self", "C", "suspension"),
  allowed("MLB2228", "car-parts.lighting.self", "B", "lighting"),
  allowed("MLB458211", "car-parts.lighting.exterior.self", "B", "lighting"),
  allowed("MLB458231", "car-parts.lighting.headlights.self", "B", "lighting"),
  allowed("MLB458234", "car-parts.lighting.interior.self", "B", "lighting"),
  allowed("MLB458243", "car-parts.lighting.turn-signals.self", "B", "lighting"),
  allowed("MLB458247", "car-parts.lighting.bulbs-leds.self", "B", "lighting"),
  allowed("MLB7863", "car-parts.lighting.front-headlights", "B", "lighting"),
  review("MLB191726", "car-parts.lighting.other-review"),
  allowed("MLB2220", "car-parts.battery", "A", "battery"),
  allowed("MLB458762", "car-parts.battery-components", "C", "battery"),
  review("MLB191833", "car-parts.other-review"),

  review("MLB243551", "motorcycle-parts.root-review", "MIXED_BRANCH_REVIEW"),
  review("MLB243165", "motorcycle-parts.filters-mixed-review", "MIXED_BRANCH_REVIEW"),
  review("MLB45558", "motorcycle-parts.brakes-mixed-review", "MIXED_BRANCH_REVIEW"),
  review("MLB3935", "motorcycle-parts.lighting-mixed-review", "MIXED_BRANCH_REVIEW"),
  review("MLB45502", "motorcycle-parts.battery-mixed-review", "MIXED_BRANCH_REVIEW"),

  review("MLB2227", "tools.root-review", "MIXED_BRANCH_REVIEW"),
  allowed("MLB440135", "tools.inflators.self", "A", "tire_inflators"),
  allowed("MLB455301", "tools.scanners.self", "B", "vehicle_tools"),
  allowed("MLB437795", "tools.inspection.self", "B", "vehicle_tools"),
  allowed("MLB455304", "tools.battery.self", "B", "vehicle_tools"),
  allowed("MLB455307", "tools.measurement.self", "B", "vehicle_tools"),
  review("MLB60658", "tools.other-review"),
  review("MLB440139", "tools.inflators-other-review"),
  review("MLB455302", "tools.scanners-other-review"),
  review("MLB455306", "tools.battery-other-review"),
  review("MLB455308", "tools.measurement-other-review"),
  review("MLB455310", "tools.inspection-other-review"),

  allowed("MLB188063", "cleaning.root", "A", "automotive_cleaning"),
  review("MLB263725", "cleaning.other-review"),

  allowed("MLB2239", "security.root", "B", "vehicle_security"),
  allowed("MLB179794", "security.extinguishers", "A", "vehicle_security"),
  allowed("MLB270295", "security.triangles", "A", "vehicle_security"),
  allowed("MLB410863", "security.emergency-kits", "A", "vehicle_security"),
  review("MLB7868", "security.other-review"),
  review("MLB440298", "security.alarms-other-review"),
  review("MLB440304", "security.locks-other-review"),

  allowed("MLB3381", "car-audio.root", "B", "car_audio"),
  allowed("MLB11883", "car-audio.remote-controls", "C", "car_audio"),
  allowed("MLB129226", "car-audio.capacitors", "C", "car_audio"),
  allowed("MLB6535", "car-audio.speaker-grilles", "C", "car_audio"),
  review("MLB3387", "car-audio.other-review"),
  review("MLB438484", "car-audio.boxes-other-review"),
  review("MLB61637", "car-audio.players-other-review"),

  allowed("MLB8531", "navigation.root", "B", "vehicle_navigation"),
  allowed("MLB45258", "navigation.maps", "C", "vehicle_navigation"),
  review("MLB8534", "navigation.other-review"),
  review("MLB49513", "navigation.accessories-other-review"),

  review("MLB1747", "car-accessories.root-review", "MIXED_BRANCH_REVIEW"),
  allowed("MLB116489", "car-accessories.reverse-camera", "B", "car_accessories"),
  allowed("MLB458031", "car-accessories.portable-charger", "A", "car_accessories"),
  allowed("MLB45905", "car-accessories.parking-sensors", "B", "car_accessories"),
  allowed("MLB73312", "car-accessories.racks.self", "B", "car_accessories"),
  allowed("MLB186150", "car-accessories.dash-camera", "B", "car_accessories"),
  allowed("MLB2219", "car-accessories.floor-mats", "A", "car_accessories"),
  allowed("MLB271611", "car-accessories.cup-holders", "B", "car_accessories"),
  allowed("MLB40411", "car-accessories.child-seats", "A", "car_accessories"),
  review("MLB114677", "car-accessories.exterior-other-review"),
  review("MLB6170", "car-accessories.interior-other-review"),
  review("MLB438074", "car-accessories.other-review"),

  review("MLB1771", "motorcycle-accessories.root-review", "MIXED_BRANCH_REVIEW"),
  allowed("MLB203101", "motorcycle-accessories.intercom", "B", "motorcycle_accessories"),
  allowed("MLB22675", "motorcycle-accessories.covers", "B", "motorcycle_accessories"),
  allowed("MLB271259", "motorcycle-accessories.hand-guards", "B", "motorcycle_accessories"),
  allowed("MLB3929", "motorcycle-accessories.helmets", "A", "motorcycle_accessories"),
  allowed("MLB3932", "motorcycle-accessories.alarms", "B", "motorcycle_accessories"),
  allowed("MLB431120", "motorcycle-accessories.saddlebags", "B", "motorcycle_accessories"),
  allowed("MLB458058", "motorcycle-accessories.portable-chargers", "A", "motorcycle_accessories"),
  allowed("MLB46596", "motorcycle-accessories.windshields", "B", "motorcycle_accessories"),
  allowed("MLB46670", "motorcycle-accessories.engine-guards", "B", "motorcycle_accessories"),
  excluded("MLB430686", "motorcycle-accessories.quad-footpegs"),
  excluded("MLB432920", "motorcycle-accessories.quad-boxes"),
  review("MLB3936", "motorcycle-accessories.other-review"),

  review("MLB260634", "performance.root-review", "MIXED_BRANCH_REVIEW"),
  allowed("MLB439460", "performance.filters-lubricants", "C", "lubricants_fluids"),
  review("MLB260635", "performance.other-review"),
  review("MLB439258", "performance.brakes-review", "LOW_BREADTH_MVP"),
  review("MLB5663", "performance.suspension-review", "LOW_BREADTH_MVP"),
  review("MLB1776", "tuning.root-review", "MIXED_BRANCH_REVIEW"),
  allowed("MLB260612", "tuning.chrome", "C", "car_accessories"),
  allowed("MLB268504", "tuning.window-film", "C", "car_accessories"),
  review("MLB1780", "tuning.other-review"),
  review("MLB455216", "toll-tags.review", "LOW_BREADTH_MVP"),
  review("MLB5802", "root-other.review", "RESIDUAL_REVIEW"),
];

const ancestorRules: AutomotiveCategoryRule[] = [
  excludedAncestor("MLB377674", "services.descendants", "SERVICE_CATEGORY"),
  excludedAncestor("MLB458209", "complete-motorcycles.descendants", "COMPLETE_VEHICLE_CATEGORY"),
  excludedAncestor("MLB419936", "heavy-parts.descendants"),
  excludedAncestor("MLB438364", "heavy-accessories.descendants"),
  excludedAncestor("MLB6005", "marine-accessories.descendants"),
  excludedAncestor("MLB456046", "marine-parts.descendants"),
  excludedAncestor("MLB45468", "gnv.descendants"),
  allowedAncestor("MLB194025", "lubricants.car-pickup.descendants", "A", "lubricants_fluids"),
  allowedAncestor("MLB439944", "lubricants.motorcycle.descendants", "A", "lubricants_fluids"),
  allowedAncestor("MLB439463", "lubricants.fluids.descendants", "B", "lubricants_fluids"),
  excludedAncestor("MLB456115", "lubricants.heavy.descendants"),
  excludedAncestor("MLB456116", "lubricants.marine.descendants"),
  excludedAncestor("MLB456130", "lubricants.agro-industrial.descendants"),
  reviewAncestor("MLB22693", "car-parts.residual-descendants"),
  allowedAncestor("MLB191834", "car-parts.filters.descendants", "A", "filters"),
  allowedAncestor("MLB6789", "car-parts.brakes.descendants", "C", "brakes"),
  allowedAncestor("MLB22648", "car-parts.suspension.descendants", "C", "suspension"),
  allowedAncestor("MLB2228", "car-parts.lighting.descendants", "C", "lighting"),
  allowedAncestor("MLB458211", "car-parts.lighting.exterior.descendants", "B", "lighting"),
  allowedAncestor("MLB458231", "car-parts.lighting.headlights.descendants", "B", "lighting"),
  allowedAncestor("MLB458234", "car-parts.lighting.interior.descendants", "B", "lighting"),
  allowedAncestor("MLB458243", "car-parts.lighting.turn-signals.descendants", "B", "lighting"),
  allowedAncestor("MLB458247", "car-parts.lighting.bulbs-leds.descendants", "B", "lighting"),
  reviewAncestor("MLB243551", "motorcycle-parts.residual-descendants"),
  reviewAncestor("MLB243165", "motorcycle-parts.filters-mixed-descendants"),
  reviewAncestor("MLB45558", "motorcycle-parts.brakes-mixed-descendants"),
  reviewAncestor("MLB3935", "motorcycle-parts.lighting-mixed-descendants"),
  reviewAncestor("MLB2227", "tools.residual-descendants"),
  allowedAncestor("MLB440135", "tools.inflators.descendants", "A", "tire_inflators"),
  allowedAncestor("MLB455301", "tools.scanners.descendants", "B", "vehicle_tools"),
  allowedAncestor("MLB437795", "tools.inspection.descendants", "B", "vehicle_tools"),
  allowedAncestor("MLB455304", "tools.battery.descendants", "B", "vehicle_tools"),
  allowedAncestor("MLB455307", "tools.measurement.descendants", "B", "vehicle_tools"),
  allowedAncestor("MLB188063", "cleaning.descendants", "A", "automotive_cleaning"),
  allowedAncestor("MLB2239", "security.descendants", "B", "vehicle_security"),
  allowedAncestor("MLB3381", "car-audio.descendants", "B", "car_audio"),
  allowedAncestor("MLB8531", "navigation.descendants", "B", "vehicle_navigation"),
  reviewAncestor("MLB1747", "car-accessories.residual-descendants"),
  allowedAncestor("MLB73312", "car-accessories.racks.descendants", "B", "car_accessories"),
  reviewAncestor("MLB1771", "motorcycle-accessories.residual-descendants"),
  reviewAncestor("MLB260634", "performance.residual-descendants"),
  reviewAncestor("MLB1776", "tuning.residual-descendants"),
];

export const AUTOMOTIVE_MLB_RULES_V1: AutomotiveClassifierRules = Object.freeze({
  classificationVersion: AUTOMOTIVE_CLASSIFICATION_VERSION,
  marketplaceKey: "MERCADO_LIVRE",
  siteId: "MLB",
  rootCategoryId: AUTOMOTIVE_ROOT_CATEGORY_ID,
  exactRules: Object.freeze(exactRules.map((rule) => Object.freeze(rule))),
  ancestorRules: Object.freeze(ancestorRules.map((rule) => Object.freeze(rule))),
});
